name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  cmake-dev:
    name: CMake dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset dev

      - name: Build
        run: cmake --build --preset dev --parallel

      - name: Test
        run: ctest --preset dev
